name = "Mediumcore"
author = "purplepentagons"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1ec3210608a197b0ffe988c819c5b598872b9de2dbea14e4cf4e54070323e41"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
