name = "Mediumcore"
author = "purplepentagons"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "258d79ea4fd68e0fe34d44b9de1d9c24208fbcf2f61a0a47aa0a8138b16c1377"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"

[options]
meta-folder = "links/"
