name = "Mediumcore"
author = "purplepentagons"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b72babe7199952898b5560ab3a7bbaf6dd038e2a950546e0a08af0a8fb4d1f42"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"

[options]
meta-folder = "links/"
